[package]
name = "tlsn-notary-client"
version = "0.1.0-alpha.5"
edition = "2021"

[features]
default = ["tracing"]
tracing = [
    "dep:tracing",
    "tlsn-common/tracing",
    "tlsn-prover/tracing"
]

[dependencies]
notary-server = { path = "../../notary-server" }
tlsn-tls-client.workspace = true
tlsn-common.workspace = true
tlsn-prover.workspace = true

derive_builder.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "net",
  "io-std",
  "fs",
] }
tokio-util.workspace = true
tracing = { workspace = true, optional = true }
webpki-roots.workspace = true

eyre = "0.6.8"
http-body-util = "0.1"
hyper = { version = "1.1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["full"] }
rustls = "0.21"
rustls-pemfile = "1.0.2"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0"
tokio-rustls = "0.24.1"
